### ISSUE TITLE
Error when using multiple Elysia instances 

### ISSUE THREAD

**Issue by justin13888** [gaurishhs/elysia-ip#13] opened 2024-03-27 04:43 UTC
![image](https://github.com/gaurishhs/elysia-ip/assets/20733699/5d39d067-a55a-4274-87b9-9b61b665005a)

elysia-ip version: 1.0.0

So you get this error whenever you write something sane like this (e.g. to separate route definitions).

```
const app = new Elysia()
  .use(cors())
  .use(login)
  .listen(envs.PORT);
 
const login = new Elysia()
    .use(ip())
    .post('/login', async ({ body, ip }) => {
        console.log(ip);
        ...
    });

export default login;
```

**Comment by gaurishhs** [comment] 2024-03-27 06:49
You will have to call the plugin for each Elysia instance. This is how plugins in Elysia work. 

For every instance where you want to use this plugin you will have to call `.use(ip())`

**Comment by gaurishhs** [comment] 2024-03-27 07:05
I can't figure this out either, You will probably have to use the plugin in the main instance i.e. where you call `.listen()`

**Comment by justin13888** [comment] 2024-03-27 18:12
Hmm...I'm thinking how it would be usable for any moderately serious application.

The elysia-ip source code is only 60 lines currently so I'll see if I could fix it for my app and perhaps make a PR later.

**Comment by justin13888** [comment] 2024-04-05 08:07
> I have a similar issue. 
> 
> When I register the plugin on the main instance, all sub-instances (in separate files) return `null` for the IP.
> 
> To take the example above:
> ```
> const app = new Elysia()
>   .use(cors())
>   .use(ip())
>   .use(login)
>   .listen(envs.PORT);
>  
> const login = new Elysia()
> 
>     .post('/login', async ({ body, ip }) => {
>         console.log(ip); // null
>         ...
>     });
> ```
> 
> Do you think this is related, or should I open a new issue? That new as: global thing is messing things up ^.^
> I'm using v1.0.11 of Elysia.

This is different because you should be instantiating the plugin/middleware wherever you intend to use it. My issue was despite using it syntactically correct, it would error out on requests because of limitations of the Elysia API. Plan to look into how to hook into the bun API under the hood without needing Elysia to start listening first. But I'm busy currently so I won't get back to it in a bit

**Comment by gaurishhs** [comment] 2024-04-06 13:44
https://elysiajs.com/essential/plugin#service-locator

The docs say this to be a Typescript limitation so i really don't think i can do anything on my part

**Comment by gaurishhs** [comment] 2024-04-06 14:18
@justin13888 After investigating this issue, I have found that this should work just fine for your case: 

```ts
import Elysia from "elysia";
import { ip } from './src/';

const login = new Elysia()
    .post('/login', async ({ body, ip }) => {
        console.log(ip);
// ...
    });



const app = new Elysia()
  .use(cors())
  .use(ip())
  .use(login)
  .listen(envs.PORT);

export default login;
```

**Comment by gaurishhs** [comment] 2024-04-06 14:19
You will have to call the plugin in the instance where `.listen()` is called.

**Comment by gaurishhs** [comment] 2024-04-06 14:23
@Extarys I'm sorry but i am unable to reproduce your issue. it works just fine on my machine.

**Comment by Extarys** [comment] 2024-04-07 09:50
thanks for taking the time to test on your end. I'll keep testing on mine, maybe my setup is different... *somehow* :P

**Comment by gaurishhs** [comment] 2024-04-10 11:31
I am closing the issue. Feel free to open a new one if something doesn't work again

**Closed by gaurishhs** 2024-04-10 11:31 UTC
