### ISSUE TITLE
Cannot find module 'elysia-ip' or its corresponding type declarations.

### ISSUE THREAD

**Issue by Mikey-ShenSu** [gaurishhs/elysia-ip#14] opened 2024-03-30 22:33 UTC
```json
{
  "name": "study-app",
  "version": "1.0.50",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "dev": "bun run --watch src/index.ts",
    "start": "NODE_ENV=production bun run src/index.ts"
  },
  "dependencies": {
    "@elysiajs/bearer": "^1.0.2",
    "@elysiajs/cors": "^1.0.2",
    "@elysiajs/jwt": "^1.0.2",
    "@elysiajs/static": "^1.0.2",
    "@elysiajs/swagger": "^0.8.5",
    "@types/pluralize": "^0.0.33",
    "elysia": "^1.0.10",
    "mongoose": "^8.2.1",
    "pluralize": "^8.0.0",
    "tencentcloud-sdk-nodejs-sms": "^4.0.789",
    "uuid": "^9.0.1"
  },
  "devDependencies": {
    "@types/uuid": "^9.0.8",
    "bun-types": "latest"
  },
  "module": "src/index.js"
}
```

I don't know what is causing the issue.

![Screenshot 2024-03-31 at 06 33 09](https://github.com/gaurishhs/elysia-ip/assets/153639584/8e7c2bcd-3c2f-48a8-bb95-5500e4ab68bb)

**Comment by gaurishhs** [comment] 2024-03-31 01:43
#12

**Comment by Mikey-ShenSu** [comment] 2024-03-31 01:59
> #12

I believe I am already in the latest version, and ```"main": "./dist/index.js"``` is added by default in the latest update, still no luck for me :(.

```json
{
  "name": "elysia-ip",
  "version": "1.0.2",
  "type": "module",
  "author": {
    "name": "Gaurish Sethia",
    "url": "https://github.com/gaurishhs",
    "email": "gaurishh.sethia@gmail.com"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/gaurishhs/elysia-ip"
  },
  "exports": {
    "main": "./dist/index.js",
    "require": "./dist/index.js",
    "import": "./dist/index.js",
    "node": "./dist/index.js",
    "default": "./dist/index.js",
    "types": "./dist/index.d.ts"
  },
  "bugs": "https://github.com/gaurishhs/elysia-ip/issues",
  "homepage": "https://github.com/gaurishhs/elysia-ip",
  "keywords": [
    "elysia",
    "typescript",
    "ip"
  ],
  "scripts": {
    "build": "tsc",
    "lint": "eslint . --ext .ts"
  },
  "license": "MIT",
  "devDependencies": {
    "@types/bun": "^1.0.2",
    "@typescript-eslint/eslint-plugin": "^6.7.4",
    "@typescript-eslint/parser": "^6.7.4",
    "elysia": "^1.0.9",
    "eslint": "^8.50.0",
    "typescript": "^5.3.3"
  },
  "peerDependencies": {
    "elysia": ">= 1.0.9"
  }
}
```

**Comment by gaurishhs** [comment] 2024-03-31 04:48
This fix worked for someone else as well which is why i published it. It follows the convention as well, so irdk what the problem might be

**Comment by RappyTV** [comment] 2024-03-31 19:54
i have the same problem and I just found a solution. i don't know why, but when I copy the `"main": "./dist/index.js"` into the "main object" (idk how to call it) it works. looks like this now:
```json
{
  "name": "elysia-ip",
  "version": "1.0.2",
  "type": "module",
  "author": {
    "name": "Gaurish Sethia",
    "url": "https://github.com/gaurishhs",
    "email": "gaurishh.sethia@gmail.com"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/gaurishhs/elysia-ip"
  },
  "main": "./dist/index.js",
  "exports": {
    "main": "./dist/index.js",
    "require": "./dist/index.js",
    "import": "./dist/index.js",
    "node": "./dist/index.js",
    "default": "./dist/index.js",
    "types": "./dist/index.d.ts"
  },
  "bugs": "https://github.com/gaurishhs/elysia-ip/issues",
  "homepage": "https://github.com/gaurishhs/elysia-ip",
  "keywords": [
    "elysia",
    "typescript",
    "ip"
  ],
  "scripts": {
    "build": "tsc",
    "lint": "eslint . --ext .ts"
  },
  "license": "MIT",
  "devDependencies": {
    "@types/bun": "^1.0.2",
    "@typescript-eslint/eslint-plugin": "^6.7.4",
    "@typescript-eslint/parser": "^6.7.4",
    "elysia": "^1.0.9",
    "eslint": "^8.50.0",
    "typescript": "^5.3.3"
  },
  "peerDependencies": {
    "elysia": ">= 1.0.9"
  }
}
```

**Comment by KwaiTushan** [comment] 2024-04-01 13:19
> i have the same problem and I just found a solution. i don't know why, but when I copy the `"main": "./dist/index.js"` into the "main object" (idk how to call it) it works. looks like this now:
> 
> ```json
> {
>   "name": "elysia-ip",
>   "version": "1.0.2",
>   "type": "module",
>   "author": {
>     "name": "Gaurish Sethia",
>     "url": "https://github.com/gaurishhs",
>     "email": "gaurishh.sethia@gmail.com"
>   },
>   "repository": {
>     "type": "git",
>     "url": "https://github.com/gaurishhs/elysia-ip"
>   },
>   "main": "./dist/index.js",
>   "exports": {
>     "main": "./dist/index.js",
>     "require": "./dist/index.js",
>     "import": "./dist/index.js",
>     "node": "./dist/index.js",
>     "default": "./dist/index.js",
>     "types": "./dist/index.d.ts"
>   },
>   "bugs": "https://github.com/gaurishhs/elysia-ip/issues",
>   "homepage": "https://github.com/gaurishhs/elysia-ip",
>   "keywords": [
>     "elysia",
>     "typescript",
>     "ip"
>   ],
>   "scripts": {
>     "build": "tsc",
>     "lint": "eslint . --ext .ts"
>   },
>   "license": "MIT",
>   "devDependencies": {
>     "@types/bun": "^1.0.2",
>     "@typescript-eslint/eslint-plugin": "^6.7.4",
>     "@typescript-eslint/parser": "^6.7.4",
>     "elysia": "^1.0.9",
>     "eslint": "^8.50.0",
>     "typescript": "^5.3.3"
>   },
>   "peerDependencies": {
>     "elysia": ">= 1.0.9"
>   }
> }
> ```

yeah it works for me too, tho idk why

**Comment by gaurishhs** [comment] 2024-04-01 17:22
I don't get it either

**Comment by RappyTV** [comment] 2024-04-09 21:16
agree

**Comment by gaurishhs** [comment] 2024-04-10 11:27
I haven't been able to understand this issue. I have made multiple commits trying to fix this since earlier versions as well. #5 seemed to work for some but soon countering that release was #8 The package.json follows the normal convention as it should so i really don't know what the issue is.

**Comment by gaurishhs** [comment] 2024-05-02 13:11
Fixed in latest version

**Closed by gaurishhs** 2024-05-02 13:11 UTC
